#!/bin/bash

# @bassmadrigal`s script https://www.linuxquestions.org/questions/slackware-14/script-for-building-a-slackbuilds-txt-4175598436/#post5661600
# 03/2023 I added "PACKAGES DEPENDEES-ON", you can modify it for your needs...
# 23/08/2024 skip folder rtz as it use different SlackBuilds Template and no info file is there
# 
echo "$(date "+%d/%m/%Y-%T")"
echo
echo
SBo() {
for i in */*; do
  # Check if the directory name is "rtz"; if yes, skip this iteration
  if [[ "$i" == rtz/* ]]; then
    continue
  fi
  
  NAME=$(echo "$i" | cut -d "/" -f2)
  FILES=$(ls -1 "$i" | tr '\n' ' ')
  source "$i/${NAME}.info"
  DEPSONN=$(cat "$i/dependees-on" | tr '\n' ' ')
  DEPSON=$(echo "$DEPSONN" | sed 's/ *$//')
  SHORTDES=$(grep -m 1 "$NAME" "$i/slack-desc" | cut -d " " -f2-)
  
  echo SLACKBUILD NAME: "$NAME" 
  echo SLACKBUILD LOCATION: "$i"
  echo SLACKBUILD FILES: "$FILES"
  echo SLACKBUILD VERSION: "$VERSION"
  echo SLACKBUILD DOWNLOAD: "$DOWNLOAD"
  echo SLACKBUILD DOWNLOAD_x86_64: "$DOWNLOAD_x86_64" 
  echo SLACKBUILD MD5SUM: "$MD5SUM" 
  echo SLACKBUILD MD5SUM_x86_64: "$MD5SUM_x86_64" 
  echo SLACKBUILD REQUIRES: "$REQUIRES" 
  echo PACKAGES DEPENDEES-ON: "$DEPSON"
  echo SLACKBUILD SHORT DESCRIPTION: "$SHORTDES" 
  echo 
done
}

custom(){
cd rtz || exit
  for sex in $(ls); do
FILES1=$(ls -1 "$sex" | tr '\n' ' ')
DEPSON1=$(cat "$sex/dependees-on" | tr '\n' ' ')
REQUIRES1=$(cat "$sex/slack-required" | tr '\n' ' ')
SUGGEST=$(cat "$sex/slack-suggests" | tr '\n' ' ')
CONFLICTS=$(cat "$sex/slack-conflicts" | tr '\n' ' ') 
SRCURL=$(sed -n 's/SRCURL=\(.*\)/\1/p' $sex/$sex.SlackBuild)
VERSION1=$(sed -n 's/VERSION=\(.*\)/\1/p' $sex/$sex.SlackBuild)
PRGNAM=$(sed -n 's/PRGNAM=\(.*\)/\1/p' $sex/$sex.SlackBuild)
SortDesc=$(sed -n 's/SortDesc="\(.*\)"/\1/p' $sex/$sex.SlackBuild)

    echo SLACKBUILD NAME: "$PRGNAM" 
    echo SLACKBUILD LOCATION: rtz/"$sex"
    echo SLACKBUILD FILES: "$FILES1"
    echo SLACKBUILD VERSION: "$VERSION1"
    echo SLACKBUILD DOWNLOAD: "$SRCURL"
    echo SLACKBUILD REQUIRES: "$REQUIRES1"
    echo SLACKBUILD SUGGESTIONS: "$SUGGEST"
    echo SLACKBUILD CONFLICTS: "$CONFLICTS"
    echo PACKAGES DEPENDEES-ON: "$DEPSON1"
    echo SLACKBUILD SHORT DESCRIPTION: "$SortDesc" 
    echo
   done
}

SBo
custom




















