#!/bin/bash

# This sqf2dep script can fork SBo repo and create package.dep and slack-required files if your package-manager need them...
# After you can use it as local repo or upload it as public if you can maintain it.
# In that case you should run this script minimum ones per week to update it. 
# Written by Anagnostakis Ioannis GR Crete <rizitis@gmail.com>
# LICENCE https://raw.githubusercontent.com/rizitis/sqf2dep/main/LICENSE
# Take the idea of script and make it better...

if [ "$EUID" -ne 0 ];then
echo "ROOT ACCESS PLEASE OR GO HOME..."
exit 1
fi

#*************************************************************************************************************************
# If you want to use ponce repo for Slackware-current, (I did it for this script), then create a file (or edit if exist) *
# /root/.sbopkg.conf                                                                                                     *
# add these 2 lines inside:                                                                                              *
# REPO_NAME=SBo-git                                                                                                      *
# REPO_BRANCH=current                                                                                                    *
#*************************************************************************************************************************

# synchronize sbopkg with remote repo 
sbopkg -r || exit
# create for all packages that need deps a package.sqf file
sqg -a
# update local Slackware system database
updatedb

# create package.dep and slack-recuired files
dir=/tmp/sqf2dep
rm -r $dir
for i in `ls /var/lib/sbopkg/queues/`; do
mkdir -p $dir || exit
mkdir -p $dir/"$i" || exit
cat /var/lib/sbopkg/queues/"$i" > $dir/"$i"/"$i"
cat /var/lib/sbopkg/queues/"$i" > $dir/"$i"/slack-recuired
cd $dir || exit
rename 'sqf' 'dep' "$i"/*.sqf
rename '.sqf' '' "$i"
done

# Here I focuss to ponce repo , for the Slackware-stable slackbuilds repo following commands need a lot of edits...
repo=/tmp/slackbuilds-current
cd /tmp || exit
rm current.zip*
# for stable replace github url and unzip command...
wget https://github.com/Ponce/slackbuilds/archive/refs/heads/current.zip
unzip current.zip
# Not needed any more
rm current.zip slackbuilds-current/README slackbuilds-current/ChangeLog.txt
cd $repo || exit
# copy paste .dep and slack-required files to the correct repo folders
for i in `ls /tmp/sqf2dep/`; do
cp /tmp/sqf2dep/"$i"/slack-recuired $repo/*/"$i"/
cp /tmp/sqf2dep/"$i"/"$i".dep $repo/*/"$i"/
done

# Make new SLACKBUILDS.TXT using @bassmadrigal script https://www.linuxquestions.org/questions/slackware-14/script-for-building-a-slackbuilds-txt-4175598436/#post5661600
repo=/tmp/slackbuilds-current
cd $repo || exit
wget https://raw.githubusercontent.com/rizitis/sqf2dep/main/create-SLACKBUILDS_TXT
chmod +x create-SLACKBUILDS_TXT
bash create-SLACKBUILDS_TXT > SLACKBUILDS.TXT
rm create-SLACKBUILDS_TXT*
echo "YOUR LOCAL REPO IS READY. IF YOU WANT TO UPLOAD IT AS A PUPLIC REPO, "
echo "PLEASE CREATE A ChangeLog.txt file and a README"
echo
sleep 3

exit
