#!/bin/bash

# Written by Anagnostakis Ioannis GR Crete <rizitis@gmail.com> 03/2023
# This sqf2dep script can fork SBo repo and create package.dep and slack-required files if your package-manager need them...
# Also will find for you the packages that dependees on "$i"package in and print "dependees-on" files in SlackBuild folder
# After all you can use it as local repo or upload it as public if you can maintain it...
# In that case you should run this script minimum ones per week to update it. 
# LICENCE https://raw.githubusercontent.com/rizitis/sqf2dep/main/LICENSE
# Take the idea of script and make it better...

if [ "$EUID" -ne 0 ];then
echo "ROOT ACCESS PLEASE OR GO HOME..."
exit 1
fi

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
#*************************************************************************************************************************
# If you want to use ponce repo for Slackware-current, (I did it for this script), then create a file (or edit if exist) *
# /root/.sbopkg.conf                                                                                                     *
# add these 2 lines inside:                                                                                              *
# REPO_NAME=SBo-git                                                                                                      *
# REPO_BRANCH=current                                                                                                    *
#*************************************************************************************************************************

# synchronize sbopkg with remote repo 
sbopkg -r || exit
# create for all packages that need deps a package.sqf file
sqg -a
rm /var/lib/sbopkg/queues/Mumble*
# update local Slackware system database
/usr/bin/updatedb

# create package.dep and slack-required files
dir=/tmp/sqf2dep
rm -r $dir
for i in `ls /var/lib/sbopkg/queues/`; do
mkdir -p $dir || exit
mkdir -p $dir/"$i" || exit
cat /var/lib/sbopkg/queues/"$i" > $dir/"$i"/"$i"
cat /var/lib/sbopkg/queues/"$i" > $dir/"$i"/slack-required
cd $dir || exit
rename 'sqf' 'dep' "$i"/*.sqf
rename '.sqf' '' "$i"
done

# Here I focuss to ponce repo , for the Slackware-stable slackbuilds repo following commands need a lot of edits...
repo=/tmp/slackbuilds-current
cd /tmp || exit
rm current.zip*
rm -r $repo
# for stable replace github url and unzip command...
wget https://github.com/Ponce/slackbuilds/archive/refs/heads/current.zip
unzip current.zip
# Not needed any more
rm current.zip slackbuilds-current/ChangeLog.txt slackbuilds-current/README
cd $repo || exit
# copy paste .dep and slack-required files to the correct repo folders but not the empty files.
for i in `ls /tmp/sqf2dep/`; do
if [[ -s "/tmp/sqf2dep/"$i"/slack-required" ]]
then
  cp /tmp/sqf2dep/"$i"/slack-required $repo/*/"$i"/
  cp /tmp/sqf2dep/"$i"/"$i".dep $repo/*/"$i"/
fi
done

#***********************************************************************#
#* slpkg time now. Make sure you have /etc/slpkg/slpkg.toml like this: *#
#* PONCE_REPO = true                                                   *#
#* COLORS = false                                                      *#
#* ASCII_CHARACTERS = false                                            *#
#***********************************************************************#

slpkg -yP update
# slpkg will find and print the packages that dependees on "$i"package
repo=/tmp/slackbuilds-current
dir=/tmp/sqf2dep
cd $repo || exit
for i in `ls /tmp/sqf2dep`; do 
slpkg -e $i >> $dir/"$i"/dependees-on
# remove last line
sed -i '$d' $dir/"$i"/dependees-on
sed -i '$d' $dir/"$i"/dependees-on
# remove 3 first lines
sed -i '1,3d' $dir/"$i"/dependees-on
# remove the specific character (+=)
sed -i 's/+=//' $dir/"$i"/dependees-on
# delete lines starting with 
sed -i '/^No/d' $dir/"$i"/dependees-on
# remove empty lines
sed -i '/^[[:space:]]*$/d' $dir/"$i"/dependees-on
# remove tabs,spaces etc...
sed -i 's/^[ \t]*//' $dir/"$i"/dependees-on
wait
if [ ! -s $dir/"$i"/dependees-on ] ; then
  rm $dir/"$i"/dependees-on
fi
# copy paste dependees-on to the correct repo folders
rsync  --inplace /tmp/sqf2dep/"$i"/dependees-on $repo/*/"$i"/
done

# Make new SLACKBUILDS.TXT using @bassmadrigal script https://www.linuxquestions.org/questions/slackware-14/script-for-building-a-slackbuilds-txt-4175598436/#post5661600
repo=/tmp/slackbuilds-current 
cd $repo || exit
wget https://raw.githubusercontent.com/rizitis/sqf2dep/main/create-SLACKBUILDS_TXT
chmod +x create-SLACKBUILDS_TXT
bash create-SLACKBUILDS_TXT > SLACKBUILDS.TXT
wait
rm create-SLACKBUILDS_TXT*


echo "sqf2dep:"
echo "YOUR LOCAL REPO IS READY. IF YOU WANT TO UPLOAD IT AS A PUPLIC REPO, "
echo "PLEASE CREATE A NEW ChangeLog.txt file and README"
echo "If you want to create a binary repo from these SlackBuilds you must edit every packages.SlackBuild"
echo "and put at least package.dep file in the installation... "
echo "If your package manager resolving deps then 'dependees-on' file might be useful too..."
echo "specially when and if you upgradepkg/removepkg package"
echo "for example, your pm may inform you which packages dependees on removable package ;) "
echo
sleep 3

exit
